auth0:
  auth0_domain:
    default: 'auth.mozilla.auth0.com'
    shadowed_by_global: true
  auth0_client_id:
    default: ''
    shadowed_by_global: true
  auth0_client_secret:
    default: ''
    shadowed_by_global: true
